sotec_web/sotec_web/Controllers/WokieeController.cs
using sotec_firma.Helpers;
using sotec_web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace sotec_web.Controllers
{
    public class WokieeController : Controller
    {
        public ActionResult ComingSoon()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Contact()
        {
            return View();
        }
        
        public ActionResult About()
        {
            return View();
        }
        
        public ActionResult LostPass()
        {
            if (Session["kullanici_id"] != null)
                return RedirectToAction("Index");
            return View();
        }
        
        public ActionResult SignIn()
        {
            if (Session["kullanici_id"] != null)
                return RedirectToAction("Index");
            return View();
        }
        
        public ActionResult SignOut()
        {
            Session["kullanici_id"] = null;
            return RedirectToAction("Index");
        }
        
        public ActionResult Register()
        {
            if (Session["kullanici_id"] != null)
                return RedirectToAction("Index");
            return View();
        }
        
        public ActionResult Acount()
        {
            if (Session["kullanici_id"] == null)
                return RedirectToAction("Index");
            return View();
        }
        
        public ActionResult Adress()
        {
            if (Session["kullanici_id"] == null)
                return RedirectToAction("Index");
            return View();
        }
        
        public ActionResult AddAdress(int id = 0)
        {
            ViewBag.adres_id = id;

            return View();
        }

        public ActionResult Page(int id = 0)
        {
            ViewBag.yazi_id = id;

            return View();
        }

        public ActionResult Wishlist()
        {
            if (Session["kullanici_id"] == null)
                return RedirectToAction("Index");
            return View();
        }

        public ActionResult Cart()
        {
            return View();
        }

        public ActionResult Blogs(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }
        
        public ActionResult Blog(int id = 0)
        {
            ViewBag.blog_id = id;

            if (SQL.get("SELECT * FROM bloglar WHERE silindi = 0 AND blog_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Blogs", new { id = 0, id2 = 0 });
            }

            return View();
        }

        public ActionResult Projects(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }

        public ActionResult Project(int id = 0)
        {
            ViewBag.proje_id = id;

            if (SQL.get("SELECT * FROM projeler WHERE silindi = 0 AND proje_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Projects", new { id = 0, id2 = 0 });
            }

            return View();
        }

        public ActionResult News(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }
        
        public ActionResult New(int id = 0)
        {
            ViewBag.haber_id = id;

            if (SQL.get("SELECT * FROM haberler WHERE silindi = 0 AND haber_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("News", new { id = 0, id2 = 0 });
            }

            return View();
        }
        
        public ActionResult Services()
        {
            return View();
        }
        
        public ActionResult Service(int id = 0)
        {
            ViewBag.hizmet_id = id;

            if (SQL.get("SELECT * FROM hizmetler WHERE silindi = 0 AND hizmet_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Services", new { id = 0, id2 = 0 });
            }

            return View();
        }

        public ActionResult Referances()
        {
            return View();
        }

        public ActionResult Referance(int id = 0)
        {
            ViewBag.hizmet_id = id;

            if (SQL.get("SELECT * FROM referanslar WHERE silindi = 0 AND hizmet_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Referances", new { id = 0, id2 = 0 });
            }

            return View();
        }

        public ActionResult Products(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }
        
        public ActionResult Product(int id = 0)
        {
            ViewBag.urun_id = id;

            if (SQL.get("SELECT * FROM urunler WHERE silindi = 0 AND urun_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Products", new { id = 0, id2 = 0 });
            }

            return View();
        }

        public ActionResult Pay(int id = 0)
        {
            ViewBag.siparis_id = id;
            DataTable dt_siparis = SQL.get("SELECT * FROM siparisler WHERE silindi = 0 AND siparis_id = " + id + " AND siparis_durumu_parametre_id = 33");
            if(dt_siparis.Rows.Count <= 0)
                return RedirectToAction("Index");

            return View();
        }

        public ActionResult Order(int id = 0)
        {
            ViewBag.siparis_id = id;
            DataTable dt_siparis = SQL.get("SELECT * FROM siparisler WHERE silindi = 0 AND siparis_id = " + id);
            if (dt_siparis.Rows.Count <= 0)
                return RedirectToAction("Index");
            return View();
        }

        public ActionResult ChangeLanguage(string language, int id = 0)
        {
            if (id != 0)
            {
                ViewBag.dil_id = id;
            }

            HttpCookie cookie;
            cookie = new HttpCookie("MultiLanguageExample");
            Thread.CurrentThread.CurrentCulture = new CultureInfo(language);
            cookie.Value = language;
            Response.SetCookie(cookie);
            if (Request.UrlReferrer != null) return Redirect(Request.UrlReferrer.LocalPath);
            return Redirect("/Wokiee/Index");
        }

        [ValidateInput(false)]
        [HttpPost]
        public string MesajGonder(string ad_soyad, string email, string mesaj, string telefon, int kullanici_id = 0, string kaynak = "", string on_bilgi = "", string on_bilgi1 = "", string on_bilgi2 = "")
        {
            if (on_bilgi.Length > 0)
                mesaj = "<strong>" + on_bilgi + "</br>" + on_bilgi1 + " Adet</br>" + on_bilgi2 + "</strong></br></br>" + mesaj;

            if (String.IsNullOrEmpty(ad_soyad) || String.IsNullOrEmpty(email) || String.IsNullOrEmpty(mesaj))
            {
                return sotec_web.Resources.Dil.Ekisk_bilgi_girdiniz_lğtfen_tüm_alanları_doldurun;
            }
            else
            {
                SQL.set("INSERT INTO mesajlar (ad_soyad, email, telefon, mesaj, hedef_kullanici_id, kaynak) VALUES ('" + ad_soyad + "', '" + email + "', '" + telefon + "', '" + mesaj + "', " + kullanici_id + ", '" + kaynak + "')");
                return Resources.Dil.Mesajınız_alındı__en_kısa_sürede_size_dönüş_yapacağız_;
            }
        }

        public ActionResult kullaniciGiris(string email, string sifre)
        {
            if (email.Length <= 0 || sifre.Length <= 0)
                return RedirectToAction("SignIn", new { hata = "E-mail ve Şifre giriniz!" });

            DataTable dt_kullanici = SQL.get("SELECT * FROM kullanicilar WHERE silindi = 0 AND email = '" + email + "' AND sifre = '" + sifre + "'");
            if (dt_kullanici.Rows.Count > 0)
            {
                Session["kullanici_id"] = dt_kullanici.Rows[0]["kullanici_id"];
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("SignIn", new { hata = "E-mail veya şifre yanlış..." });
        }

        public ActionResult kullaniciEkle(string ad, string soyad, string telefon, string email, string sifre, int tip_parametre_id = 2)
        {
            if (ad.Length <= 0)
                return RedirectToAction("Register", new { hata = "Ad giriniz!" });
            if (soyad.Length <= 0)
                return RedirectToAction("Register", new { hata = "Soyad giriniz!" });
            if (email.Length <= 0)
                return RedirectToAction("Register", new { hata = "EMail giriniz!" });
            if (sifre.Length <= 0)
                return RedirectToAction("Register", new { hata = "Şifre giriniz!" });

            DataTable dt = SQL.get("SELECT * FROM kullanicilar WHERE silindi = 0 AND email = '" + email + "'");
            if (dt.Rows.Count > 0)
                return RedirectToAction("Register", new { hata = "Girdiğiniz E-Mail kullanılmaktadır!" });

            dt = SQL.get("INSERT INTO kullanicilar (kaydeden_kullanici_id, email, sifre, ad, soyad, kullanici_tipi_parametre_id, telefon) VALUES (0, '" + email + "', '" + sifre + "', '" + ad + "', '" + soyad + "', " + tip_parametre_id + ", '" + telefon + "'); SELECT SCOPE_IDENTITY();");
            Session["kullanici_id"] = dt.Rows[0][0];
            return RedirectToAction("Acount");
        }

        [HttpPost]
        public ActionResult kullaniciDuzenle(int kullanici_id, string ad, string soyad, string telefon, string email, string eski_sifre, string yeni_sifre, int tip_parametre_id = 2)
        {
            if (ad.Length <= 0)
                return RedirectToAction("Acount", new { hata = "Ad giriniz!" });

sotec_web/sotec_web/Views/Wokiee/Acount.cshtml
@using System.Data
@using sotec_firma.Helpers
@{
    ViewBag.Title = sotec_web.Resources.Dil.HESAP;

    int kullanici_id = Convert.ToInt32(Session["kullanici_id"]);
    DataRow dr_kullanici = null;
    if (kullanici_id != 0) { dr_kullanici = SQL.get("SELECT * FROM kullanicilar WHERE kullanici_id = " + kullanici_id).Rows[0]; }

    DataTable dt_siparisler = SQL.get("SELECT TOP 25 s.kargo_no, s.siparis_id, s.kayit_tarihi, s.siparis_durumu_parametre_id, s.odeme_tipi_parametre_id, toplam = ISNULL((SELECT SUM(sk.miktar * sk.birim_fiyat) FROM siparis_kalemleri sk WHERE sk.silindi = 0 AND sk.siparis_id = s.siparis_id), 0) FROM siparisler s WHERE s.silindi = 0 AND s.kullanici_id = " + dr_kullanici["kullanici_id"] + " ORDER by s.siparis_id DESC");
}
<div class="container-indent">
    <div class="container container-fluid-custom-mobile-padding">
        <h1 class="tt-title-subpages noborder">@sotec_web.Resources.Dil.HESAP</h1>
        <div class="tt-shopping-layout">
            <h2 class="tt-title-border">@sotec_web.Resources.Dil.HESAP</h2>
            <div class="tt-wrapper">
                <h3 class="tt-title">@sotec_web.Resources.Dil.SİPARİŞLER</h3>
                <div class="tt-table-responsive">
                    <table class="tt-table-shop-01">
                        <thead>
                            <tr>
                                <th>@sotec_web.Resources.Dil.SİPARİŞ</th>
                                <th>@sotec_web.Resources.Dil.TARİH</th>
                                <th>@sotec_web.Resources.Dil.DURUM</th>
                                <th>@sotec_web.Resources.Dil.ÖDEME_TİPİ</th>
                                <th>@sotec_web.Resources.Dil.KARGO</th>
                                <th>@sotec_web.Resources.Dil.TOPLAM</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow dr_siparis in dt_siparisler.Rows)
                            {
                            <tr>
                                <td><a href="@Url.Action("Order", "Wokiee", new { id = dr_siparis["siparis_id"]})">#@dr_siparis["siparis_id"]</a></td>
                                <td>@dr_siparis["kayit_tarihi"]</td>
                                <td>
                                    @switch (Convert.ToInt32(dr_siparis["siparis_durumu_parametre_id"]))
                                    {
                                        case 33:
                                            @sotec_web.Resources.Dil.BEKLEMEDE;
                                            break;
                                        case 34:
                                            @sotec_web.Resources.Dil.HAZIRLANIYOR;
                                            break;
                                        case 36:
                                            @sotec_web.Resources.Dil.KARGODA;
                                            break;
                                        case 37:
                                            @sotec_web.Resources.Dil.TAMAMLANDI;
                                            break;
                                        case 38:
                                            @sotec_web.Resources.Dil.İPTAL_EDİLDİ;
                                            break;
                                        default:
                                            @sotec_web.Resources.Dil.BEKLEMEDE;
                                            break;
                                    }
                                </td>
                                <td>
                                    @switch (Convert.ToInt32(dr_siparis["odeme_tipi_parametre_id"]))
                                    {
                                        case 29:
                                            @sotec_web.Resources.Dil.KREDİ_KARTI;
                                            break;
                                        case 30:
                                            @sotec_web.Resources.Dil.KAPIDA_ÖDEME;
                                            break;
                                        case 31:
                                            @sotec_web.Resources.Dil.MAĞAZADAN_TESLİM;
                                            break;
                                        case 32:
                                            @sotec_web.Resources.Dil.HAVALE;
                                            break;
                                        default:
                                            @sotec_web.Resources.Dil.KREDİ_KARTI;
                                            break;
                                    }
                                </td>
                                <td>@dr_siparis["kargo_no"]</td>
                                <td>@Convert.ToDecimal(dr_siparis["toplam"]).ToString("n2") ₺</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tt-wrapper">
                <h3 class="tt-title">@sotec_web.Resources.Dil.HESAP_DETAYLARI</h3>
                <a href="@Url.Action("Adress", "Wokiee")" class="btn btn-border">@sotec_web.Resources.Dil.ADRESLERİ_DÜZENLE</a>
                <div class="tt-table-responsive">
                    <form action="/Wokiee/kullaniciDuzenle" enctype="multipart/form-data" method="post">
                        <input type="hidden" name="kullanici_id" value="@dr_kullanici["kullanici_id"]" />
                        <label class="text-danger">@Request.Params["hata"]</label>
                        <table class="tt-table-shop-02">
                            <tbody>
                                <tr>
                                    <td>@sotec_web.Resources.Dil.AD:</td>
                                    <td><input type="text" name="ad" class="form-control" id="ad" placeholder="@sotec_web.Resources.Dil.AD" value="@dr_kullanici["ad"]" autocomplete="off" required></td>
                                </tr>
                                <tr>
                                    <td>@sotec_web.Resources.Dil.SOYAD:</td>
                                    <td><input type="text" name="soyad" class="form-control" id="soyad" placeholder="@sotec_web.Resources.Dil.SOYAD" value="@dr_kullanici["soyad"]" autocomplete="off" required></td>
                                </tr>
                                <tr>
                                    <td>@sotec_web.Resources.Dil.E_MAİL:</td>
                                    <td><input type="email" name="email" class="form-control" id="email" placeholder="@sotec_web.Resources.Dil.E_MAİL" value="@dr_kullanici["email"]" autocomplete="off" disabled required></td>
                                </tr>
                                <tr>
                                    <td>@sotec_web.Resources.Dil.TELEFON:</td>
                                    <td><input type="tel" name="telefon" class="form-control" id="telefon" placeholder="@sotec_web.Resources.Dil.TELEFON" value="@dr_kullanici["telefon"]" autocomplete="off" required></td>
                                </tr>
                                <tr>
                                    <td>@sotec_web.Resources.Dil.ESKİ_ŞİFRE:</td>
                                    <td><input type="password" name="eski_sifre" class="form-control" id="sifre" placeholder="@sotec_web.Resources.Dil.ESKİ_ŞİFRE" value="" autocomplete="off" required></td>
                                </tr>
                                <tr>
                                    <td>@sotec_web.Resources.Dil.YENİ_ŞİFRE:</td>
                                    <td><input type="password" name="yeni_sifre" class="form-control" id="sifre" placeholder="@sotec_web.Resources.Dil.YENİ_ŞİFRE" value="" autocomplete="off" required></td>
                                </tr>
                                <tr>
                                    <td colspan="2"><button class="btn btn-border" type="submit">@sotec_web.Resources.Dil.GÜNCELLE</button></td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

sotec_web/sotec_web/Views/Wokiee/AddAdress.cshtml
@using System.Data
@using sotec_firma.Helpers
@{
    ViewBag.Title = sotec_web.Resources.Dil.ADRES;

    int adres_id = ViewBag.adres_id;

    int kullanici_id = Convert.ToInt32(Session["kullanici_id"]);
    DataRow dr_kullanici = null;
    if (kullanici_id != 0) { dr_kullanici = SQL.get("SELECT * FROM kullanicilar WHERE kullanici_id = " + kullanici_id).Rows[0]; }
    DataRow dr_adres = null;
    if (adres_id != 0) { dr_adres = SQL.get("SELECT * FROM adresler WHERE adres_id = " + adres_id).Rows[0]; }
}
<div class="container-indent">
    <div class="container container-fluid-custom-mobile-padding">
        <h1 class="tt-title-subpages noborder">@sotec_web.Resources.Dil.ADRES</h1>
        <div class="tt-shopping-layout">
            <h2 class="tt-title">@sotec_web.Resources.Dil.ADRES</h2>
            <div class="tt-wrapper">
                <a href="@Url.Action("Adress", "Wokiee")" class="tt-link-back">
                    <i class="icon-h-46"></i> @sotec_web.Resources.Dil.GERİ
                </a>,
            </div>
            <label class="text-danger">@Request.Params["hata"]</label>
            <div class="tt-wrapper">
                <h6 class="tt-title">@sotec_web.Resources.Dil.DÜZENLE</h6>
                <div class="form-default">
                    <form method="post" action="/Wokiee/adresEkle">
                        <input type="hidden" name="kullanici_id" value="@dr_kullanici["kullanici_id"]" />
                        <input type="hidden" name="adres_id" value="@adres_id" />
                        <div class="form-group">
                            <label for="shopInputFirstName" class="control-label">@sotec_web.Resources.Dil.ADRES_ADI *</label>
                            <input type="text" class="form-control" id="ad" name="ad" value="@(adres_id == 0 ? "" : dr_adres["ad"])">
                        </div>
                        <div class="form-group">
                            <label for="shopInputLastName" class="control-label">@sotec_web.Resources.Dil.AD_SOYAD *</label>
                            <input type="text" class="form-control" id="alici" name="alici" value="@(adres_id == 0 ? "" : dr_adres["alici"])">
                        </div>
                        <div class="form-group">
                            <label for="shopCompanyName" class="control-label">@sotec_web.Resources.Dil.TELEFON</label>
                            <input type="text" class="form-control" id="telefon" name="telefon" value="@(adres_id == 0 ? "" : dr_adres["telefon"])">
                        </div>
                        <div class="form-group">
                            <label for="shopCompanyName" class="control-label">@sotec_web.Resources.Dil.ÜLKE *</label>
                            <input type="text" class="form-control" id="ulke" name="ulke" value="@(adres_id == 0 ? "" : dr_adres["ulke"])">
                        </div>
                        <div class="form-group">
                            <label for="shopAddress" class="control-label">@sotec_web.Resources.Dil.ŞEHİR *</label>
                            <input type="text" class="form-control" id="sehir" name="sehir" value="@(adres_id == 0 ? "" : dr_adres["sehir"])">
                        </div>
                        <div class="form-group">
                            <label for="shopTown" class="control-label">@sotec_web.Resources.Dil.SEMT *</label>
                            <input type="text" class="form-control" id="semt" name="semt" value="@(adres_id == 0 ? "" : dr_adres["semt"])">
                        </div>
                        <div class="form-group">
                            <label for="shopState" class="control-label">@sotec_web.Resources.Dil.ADRES *</label>
                            <input type="text" class="form-control" id="adres" name="adres" value="@(adres_id == 0 ? "" : dr_adres["adres"])">
                        </div>
                        <div class="form-group">
                            <label for="shopPostCode" class="control-label">@sotec_web.Resources.Dil.POSTA_KODU</label>
                            <input type="text" class="form-control" id="posta_kodu" name="posta_kodu" value="@(adres_id == 0 ? "" : dr_adres["posta_kodu"])">
                        </div>
                        <div class="row tt-offset-21">
                            <div class="col-auto">
                                <button type="submit" class="btn">@sotec_web.Resources.Dil.KAYDET</button>
                            </div>
                            <div class="col-auto align-self-center">
                                <a href="@Url.Action("Adress", "Wokiee")" class="tt-link">@sotec_web.Resources.Dil.GERİ</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

sotec_web/sotec_web/Views/Wokiee/Contact.cshtml
@using System.Data
@using sotec_firma.Helpers
@{
    ViewBag.Title = sotec_web.Resources.Dil.İLETİŞİM;

    string lang = Request.Cookies.Get("MultiLanguageExample").Value;

    DataTable dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND kisa_kod = '" + lang + "'");
    if (dt_dil.Rows.Count <= 0) { dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND varsayilan = 1"); }
    DataRow dr_dil = dt_dil.Rows[0];

    DataRow dr_site_bilgileri = SQL.get("SELECT * FROM site_bilgileri WHERE dil_id = " + dr_dil["dil_id"]).Rows[0];
}
<div class="container-indent">
    <div class="container container-fluid-custom-mobile-padding">
        <div class="tt-contact02-col-list">
            <div class="row">
                <div class="col-sm-12 col-md-4 ml-sm-auto mr-sm-auto">
                    <div class="tt-contact-info">
                        <i class="tt-icon icon-f-93"></i>
                        <h6 class="tt-title">@sotec_web.Resources.Dil.İLETİŞİM</h6>
                        <address>
                            @MvcHtmlString.Create((dr_site_bilgileri["telefon"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.TELEFON + ": </span>" + dr_site_bilgileri["telefon"] + "</p>"))
                            @MvcHtmlString.Create((dr_site_bilgileri["gsm"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.GSM + ": </span>" + dr_site_bilgileri["gsm"] + "</p>"))
                            @MvcHtmlString.Create((dr_site_bilgileri["fax"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.FAX + ": </span>" + dr_site_bilgileri["fax"] + "</p>"))
                            @MvcHtmlString.Create((dr_site_bilgileri["whatsapp"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.WHATSAPP + ": </span>" + dr_site_bilgileri["whatsapp"] + "</p>"))
                            @MvcHtmlString.Create((dr_site_bilgileri["email"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.E_MAİL + ": </span> <a href='mailto: " + dr_site_bilgileri["email"] + "'>" + dr_site_bilgileri["email"] + "</a></p>"))
                        </address>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="tt-contact-info">
                        <i class="tt-icon icon-f-24"></i>
                        <h6 class="tt-title">@sotec_web.Resources.Dil.ADRES</h6>
                        <address>
                            @MvcHtmlString.Create((dr_site_bilgileri["adres"].ToString().Length <= 0 ? "" : "<p>" + dr_site_bilgileri["adres"] + "</p>"))
                        </address>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="tt-contact-info">
                        <i class="tt-icon icon-f-92"></i>
                        <h6 class="tt-title">@sotec_web.Resources.Dil.ÇALIŞMA_SAATLERİ</h6>
                        <address>
                            @MvcHtmlString.Create((dr_site_bilgileri["calisma_saatleri"].ToString().Length <= 0 ? "" : "<p>" + dr_site_bilgileri["calisma_saatleri"] + "</p>"))
                        </address>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-indent">
    <div class="container container-fluid-custom-mobile-padding">
        @using (Ajax.BeginForm("MesajGonder", "Wokiee", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divSonuc", OnSuccess = "onAjaxRequestSuccess" }, new { id = "formKapsayici" }))
        {
            <div class="row text-danger" id="divSonuc"></div>
            <div class="row">
                <div class="col-md-6">
                    <input type="hidden" name="kaynak" value="İletişim" />
                    <div class="form-group">
                        <input type="text" name="ad_soyad" class="form-control" id="form-blog-reply-name" placeholder="@sotec_web.Resources.Dil.AD_SOYAD *" required>
                    </div>
                    <div class="form-group">
                        <input type="text" name="email" class="form-control" id="form-blog-reply-email" placeholder="@sotec_web.Resources.Dil.E_MAİL *" required>
                    </div>
                    <div class="form-group">
                        <input type="text" name="telefon" class="form-control" id="form-blog-reply-telefon" placeholder="@sotec_web.Resources.Dil.TELEFON">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <textarea name="mesaj" class="form-control" rows="7" placeholder="@sotec_web.Resources.Dil.MESAJ" id="form-blog-reply-message" required></textarea>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button type="submit" id="form-blog-reply-submit" class="btn">@sotec_web.Resources.Dil.GÖNDER</button>
            </div>
        }
    </div>
</div>

sotec_web/sotec_web/Views/Wokiee/LostPass.cshtml
@{
    ViewBag.Title = "LossPass";
}

<h2>LossPass</h2>

sotec_web/sotec_web/Views/Wokiee/Register.cshtml
@{
    ViewBag.Title = sotec_web.Resources.Dil.KAYIT_OL;
}
<div class="container-indent">
    <div class="container">
        <h1 class="tt-title-subpages noborder">@sotec_web.Resources.Dil.KAYIT_OL</h1>
        <div class="tt-login-form">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6">
                    <div class="tt-item">
                        <h2 class="tt-title">@sotec_web.Resources.Dil.KAYIT_OL</h2>
                        <div class="form-default">
                            @using (Html.BeginForm("kullaniciEkle", "Wokiee", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                            {
                                <label class="text-danger">@Request.Params["hata"]</label>
                                <div class="form-group">
                                    <label for="loginInputName">@sotec_web.Resources.Dil.AD *</label>
                                    <div class="tt-required">* Required Fields</div>
                                    <input type="text" name="ad" class="form-control" id="ad" placeholder="@sotec_web.Resources.Dil.AD" autocomplete="off" required>
                                </div>
                                <div class="form-group">
                                    <label for="loginLastName">@sotec_web.Resources.Dil.SOYAD *</label>
                                    <input type="text" name="soyad" class="form-control" id="soyad" placeholder="@sotec_web.Resources.Dil.SOYAD" autocomplete="off" required>
                                </div>
                                <div class="form-group">
                                    <label for="loginInputEmail">@sotec_web.Resources.Dil.E_MAİL *</label>
                                    <input type="email" name="email" class="form-control" id="email" placeholder="@sotec_web.Resources.Dil.E_MAİL" autocomplete="off" required>
                                </div>
                                <div class="form-group">
                                    <label for="loginInputEmail">@sotec_web.Resources.Dil.TELEFON *</label>
                                    <input type="tel" name="telefon" class="form-control" id="telefon" placeholder="@sotec_web.Resources.Dil.TELEFON" autocomplete="off" required>
                                </div>
                                <div class="form-group">
                                    <label for="loginInputPassword">@sotec_web.Resources.Dil.ŞİFRE *</label>
                                    <input type="password" name="sifre" class="form-control" id="sifre" placeholder="@sotec_web.Resources.Dil.ŞİFRE" autocomplete="off" required>
                                </div>
                                <div class="row">
                                    <div class="col-auto">
                                        <div class="form-group">
                                            <button class="btn btn-border" type="submit">@sotec_web.Resources.Dil.KAYIT_OL</button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>