sotec_web/sotec_web/Controllers/InteshapeController.cs
using sotec_firma.Helpers;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace sotec_web.Controllers
{
    public class InteshapeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ComingSoon()
        {
            return View();
        }

        [Route("Contact")]
        public ActionResult Contact()
        {
            return View();
        }

        [Route("About")]
        public ActionResult About()
        {
            return View();
        }

        [Route("Projects")]
        [Route("Projects/{id}")]
        [Route("Projects/{id}/{id2}")]
        public ActionResult Projects(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }

        [Route("Project/{id}")]
        public ActionResult Project(int id = 0)
        {
            ViewBag.proje_id = id;

            if (SQL.get("SELECT * FROM projeler WHERE silindi = 0 AND proje_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Projects", new { id = 0, id2 = 0 });
            }

            return View();
        }

        [Route("Services")]
        public ActionResult Services()
        {
            return View();
        }

        [Route("Service/{id}")]
        public ActionResult Service(int id = 0)
        {
            ViewBag.hizmet_id = id;

            if (SQL.get("SELECT * FROM hizmetler WHERE silindi = 0 AND hizmet_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Services", new { id = 0, id2 = 0 });
            }

            return View();
        }

        [Route("Referances")]
        public ActionResult Referances()
        {
            return View();
        }

        [Route("Referance/{id}")]
        public ActionResult Referance(int id = 0)
        {
            ViewBag.referans_id = id;

            if (SQL.get("SELECT * FROM referanslar WHERE silindi = 0 AND referans_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Referances", new { id = 0, id2 = 0 });
            }

            return View();
        }

        [Route("Blogs")]
        [Route("Blogs/{id}")]
        [Route("Blogs/{id}/{id2}")]
        public ActionResult Blogs(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }

        [Route("Blog/{id}")]
        public ActionResult Blog(int id = 0)
        {
            ViewBag.blog_id = id;

            if (SQL.get("SELECT * FROM bloglar WHERE silindi = 0 AND blog_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Blogs", new { id = 0, id2 = 0 });
            }

            return View();
        }

        [Route("Products")]
        [Route("Products/{id}")]
        [Route("Products/{id}/{id2}")]
        public ActionResult Products(int id = 0, int id2 = 0)
        {
            ViewBag.sayfa_no = id;
            ViewBag.kategori_id = id2;

            return View();
        }

        [Route("Product/{id}")]
        public ActionResult Product(int id = 0)
        {
            ViewBag.urun_id = id;

            if (SQL.get("SELECT * FROM urunler WHERE silindi = 0 AND urun_id = " + id).Rows.Count <= 0)
            {
                return RedirectToAction("Products", new { id = 0, id2 = 0 });
            }

            return View();
        }

        public ActionResult ChangeLanguage(string language, int id = 0)
        {
            if (id != 0)
            {
                ViewBag.dil_id = id;
            }

            HttpCookie cookie;
            cookie = new HttpCookie("MultiLanguageExample");
            Thread.CurrentThread.CurrentCulture = new CultureInfo(language);
            cookie.Value = language;
            Response.SetCookie(cookie);
            if (Request.UrlReferrer != null) return Redirect(Request.UrlReferrer.LocalPath);
            return Redirect("/Inteshape/Index");
        }

        [ValidateInput(false)]
        [HttpPost]
        public string MesajGonder(string ad_soyad, string email, string mesaj, string telefon, int kullanici_id = 0, string kaynak = "", string on_bilgi = "", string on_bilgi1 = "", string on_bilgi2 = "")
        {
            if (on_bilgi.Length > 0)
                mesaj = "<strong>" + on_bilgi + "</br>" + on_bilgi1 + " Adet</br>" + on_bilgi2 + "</strong></br></br>" + mesaj;

            if (String.IsNullOrEmpty(ad_soyad) || String.IsNullOrEmpty(email) || String.IsNullOrEmpty(mesaj))
            {
                return sotec_web.Resources.Dil.Ekisk_bilgi_girdiniz_lğtfen_tüm_alanları_doldurun;
            }
            else
            {
                SQL.set("INSERT INTO mesajlar (ad_soyad, email, telefon, mesaj, hedef_kullanici_id, kaynak) VALUES ('" + ad_soyad + "', '" + email + "', '" + telefon + "', '" + mesaj + "', " + kullanici_id + ", '" + kaynak + "')");
                return Resources.Dil.Mesajınız_alındı__en_kısa_sürede_size_dönüş_yapacağız_;
            }
        }
    }
}

sotec_web/sotec_web/Views/Inteshape/About.cshtml
@using System.Data
@using sotec_firma.Helpers
@{
    ViewBag.Title = sotec_web.Resources.Dil.HAKKIMIZDA;

    string lang = Request.Cookies.Get("MultiLanguageExample").Value;

    DataTable dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND kisa_kod = '" + lang + "'");
    if (dt_dil.Rows.Count <= 0) { dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND varsayilan = 1"); }
    DataRow dr_dil = dt_dil.Rows[0];

    DataRow dr_site_bilgileri = SQL.get("SELECT * FROM site_bilgileri WHERE dil_id = " + dr_dil["dil_id"]).Rows[0];
}
<div class="sx-bnr-inr overlay-wraper bg-parallax bg-top-center" data-stellar-background-ratio="0.5" style="background-image:url(images/banner/5.jpg);">
    <div class="overlay-main bg-black opacity-07"></div>
    <div class="container">
        <div class="sx-bnr-inr-entry">
            <div class="banner-title-outer">
                <div class="banner-title-name">
                    <h2 class="m-tb0">@sotec_web.Resources.Dil.HAKKIMIZDA</h2>
                </div>
            </div>
            <div>
                <ul class="sx-breadcrumb breadcrumb-style-2">
                    <li><a href="@Url.Action("Index", "Inteshape")">@sotec_web.Resources.Dil.ANA_SAYFA</a></li>
                    <li>@sotec_web.Resources.Dil.HAKKIMIZDA</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="section-full mobile-page-padding p-t80 p-b80 bg-gray">
    <div class="container">
        <div class="section-content">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-12 ">
                    <div class="home-2-about bg-center bg-no-repeat" style="background-image:url(/admin_src/images/site_logo/@dr_site_bilgileri["logo"]);">
                    </div>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-12">
                    <div class="about-home-2">
                        <h3 class="m-t0 sx-tilte">@dr_site_bilgileri["slogan"]</h3>
                        <p>@dr_site_bilgileri["hakkimizda"]</p>
                        <div class="text-left">
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

sotec_web/sotec_web/Views/Inteshape/Blog.cshtml
@using System.Data
@using sotec_firma.Helpers
@using System.Text.RegularExpressions
@{
    string lang = Request.Cookies.Get("MultiLanguageExample").Value;

    DataTable dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND kisa_kod = '" + lang + "'");
    if (dt_dil.Rows.Count <= 0) { dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND varsayilan = 1"); }
    DataRow dr_dil = dt_dil.Rows[0];

    int blog_id = ViewBag.blog_id;

    Regex rRemScript = new Regex(@"<iframe[^>]*>[\s\S]*?</iframe>");
    string yazi;

    DataRow dr_blog = SQL.get("SELECT b.blog_id, b.gorsel, baslik = ISNULL(db.baslik, b.baslik), yazi = ISNULL(db.yazi, b.yazi), ad_soyad = k.ad + ' ' + k.soyad, b.kayit_tarihi, kategori = ISNULL(dk.kategori, kat.kategori), b.kategori_id FROM bloglar b INNER JOIN kullanicilar k ON k.kullanici_id = b.kaydeden_kullanici_id INNER JOIN kategoriler kat ON kat.kategori_id = b.kategori_id LEFT OUTER JOIN dil_kategoriler dk ON dk.kategori_id = kat.kategori_id AND dk.silindi = 0 AND dk.dil_id = " + dr_dil["dil_id"] + " LEFT OUTER JOIN dil_bloglar db ON db.blog_id = b.blog_id AND db.silindi = 0 AND db.dil_id = " + dr_dil["dil_id"] + " WHERE b.silindi = 0 AND b.blog_id = " + blog_id).Rows[0];
    DataTable dt_son_bloglar = SQL.get("SELECT TOP 3 b.blog_id, b.gorsel, baslik = ISNULL(db.baslik, b.baslik), yazi = ISNULL(db.yazi, b.yazi), ad_soyad = k.ad + ' ' + k.soyad, b.kayit_tarihi  FROM bloglar b INNER JOIN kullanicilar k ON k.kullanici_id = b.kaydeden_kullanici_id LEFT OUTER JOIN dil_bloglar db ON db.blog_id = b.blog_id AND db.silindi = 0 AND db.dil_id = " + dr_dil["dil_id"] + " WHERE b.silindi = 0 ORDER by b.blog_id DESC");

    ViewBag.Title = dr_blog["baslik"];
}
<div class="sx-bnr-inr overlay-wraper bg-parallax bg-top-center" data-stellar-background-ratio="0.5" style="background-image:url(images/banner/10.jpg);">
    <div class="overlay-main bg-black opacity-07"></div>
    <div class="container">
        <div class="sx-bnr-inr-entry">
            <div class="banner-title-outer">
                <div class="banner-title-name">
                    <h2 class="m-tb0">@dr_blog["baslik"]</h2>
                </div>
            </div>
            <div>
                <ul class="sx-breadcrumb breadcrumb-style-2">
                    <li><a href="@Url.Action("Index", "Inteshape")">@sotec_web.Resources.Dil.ANA_SAYFA</a></li>
                    <li><a href="@Url.Action("Blogs", "Inteshape")">@sotec_web.Resources.Dil.BLOG</a></li>
                    <li>@dr_blog["baslik"]</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="section-full p-t80 p-b50 inner-page-padding">
    <div class="container">
        <div class="blog-single-space max-w900 ml-auto mr-auto">
            <div class="blog-post blog-detail text-black">
                <div class="sx-post-media">
                    <div class="portfolio-item">
                        <img class="img-responsive" src="~/admin_src/images/blog/buyuk/@dr_blog["gorsel"]" alt="">
                    </div>
                </div>
                <div class="sx-post-meta  m-t20">
                    <ul>
                        <li class="post-date">@(Convert.ToDateTime(dr_blog["kayit_tarihi"]).ToShortDateString()) </li>
                        <li class="post-author">@dr_blog["ad_soyad"] </li>
                        <li class="post-category"><a href="@Url.Action("Blogs", new { id = 0, id2 = dr_blog["kategori_id"] })">@dr_blog["kategori"]</a> </li>
                    </ul>
                </div>
                <div class="sx-post-title ">
                    <h3 class="post-title">@dr_blog["baslik"]</h3>
                </div>
                <div class="sx-post-text">
                    @MvcHtmlString.Create(dr_blog["yazi"].ToString())
                </div>
                <div class="section-head">
                    <div class="sx-separator-outer separator-left">
                        <div class="sx-separator bg-white bg-moving bg-repeat-x" style="background-image:url(images/background/cross-line2.png)">
                            <h3 class="sep-line-one">@sotec_web.Resources.Dil.SON_BLOG_YAZILARI</h3>
                        </div>
                    </div>
                </div>
                <div class="section-content">
                    <div class="row">
                        @foreach (DataRow dr_blog_item in dt_son_bloglar.Rows)
                        {
                            <div class="col-md-4 col-sm-12">
                                <div class="blog-post blog-grid date-style-2">
                                    <div class="sx-post-media sx-img-effect img-reflection">
                                        <a href="@Url.Action("Blog", "Inteshape", new { id = dr_blog_item["blog_id"] })"><img src="~/admin_src/images/blog/kucuk/@dr_blog_item["gorsel"]" alt=""></a>
                                    </div>
                                    <div class="sx-post-info p-t30">
                                        <div class="sx-post-meta ">
                                            <ul>
                                                <li class="post-date">@(Convert.ToDateTime(dr_blog_item["kayit_tarihi"]).ToShortDateString())</li>
                                                <li class="post-author">@dr_blog_item["ad_soyad"]</li>
                                            </ul>
                                        </div>
                                        <div class="sx-post-title ">
                                            <h4 class="post-title"><a href="@Url.Action("Blog", "Inteshape", new { id = dr_blog_item["blog_id"] })">@dr_blog_item["baslik"]</a></h4>
                                        </div>
                                        <div class="sx-post-readmore">
                                            <a href="@Url.Action("Blog", "Inteshape", new { id = dr_blog_item["blog_id"] })" title="@sotec_web.Resources.Dil.DEVAMINI_OKU" rel="bookmark" class="site-button-link">@sotec_web.Resources.Dil.DEVAMINI_OKU</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

sotec_web/sotec_web/Views/Inteshape/Blogs.cshtml
@using System.Data
@using sotec_firma.Helpers
@using System.Text.RegularExpressions
@{
    ViewBag.Title = sotec_web.Resources.Dil.BLOG;

    string lang = Request.Cookies.Get("MultiLanguageExample").Value;

    DataTable dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND kisa_kod = '" + lang + "'");
    if (dt_dil.Rows.Count <= 0) { dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND varsayilan = 1"); }
    DataRow dr_dil = dt_dil.Rows[0];

    int sayfa_no = ViewBag.sayfa_no;
    int kategori_id = ViewBag.kategori_id;

    Regex rRemScript = new Regex(@"<iframe[^>]*>[\s\S]*?</iframe>");
    string yazi;

    int cnt_blog = Convert.ToInt32(SQL.get("SELECT cnt = COUNT(*) FROM bloglar b WHERE b.silindi = 0 " + (kategori_id == 0 ? "" : " AND b.kategori_id = " + kategori_id + " ")).Rows[0]["cnt"]);
    int sayfa_sayisi = Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(cnt_blog) / 10));

    DataTable dt_son_bloglar = SQL.get("SELECT b.blog_id, b.gorsel, baslik = ISNULL(db.baslik, b.baslik), yazi = ISNULL(db.yazi, b.yazi), ad_soyad = k.ad + ' ' + k.soyad, b.kayit_tarihi, kategori = ISNULL(dk.kategori, kat.kategori), b.kategori_id FROM bloglar b INNER JOIN kullanicilar k ON k.kullanici_id = b.kaydeden_kullanici_id INNER JOIN kategoriler kat ON kat.kategori_id = b.kategori_id LEFT OUTER JOIN dil_kategoriler dk ON dk.kategori_id = kat.kategori_id AND dk.silindi = 0 AND dk.dil_id = " + dr_dil["dil_id"] + " LEFT OUTER JOIN dil_bloglar db ON db.blog_id = b.blog_id AND db.silindi = 0 AND db.dil_id = " + dr_dil["dil_id"] + " WHERE b.silindi = 0 " + (kategori_id == 0 ? "" : " AND b.kategori_id = " + kategori_id + " ") + " ORDER by b.blog_id DESC OFFSET " + (sayfa_no * 10) + " ROWS FETCH NEXT 10 ROWS ONLY");
    DataTable dt_haber_kategori = SQL.get("SELECT k.kategori_id, kategori = ISNULL(dk.kategori, k.kategori) FROM kategoriler k LEFT OUTER JOIN dil_kategoriler dk ON dk.kategori_id = k.kategori_id AND dk.silindi = 0 AND dk.dil_id = " + dr_dil["dil_id"] + " WHERE k.silindi = 0 AND k.kategori_tipi_parametre_id = 18");
}
<div class="sx-bnr-inr overlay-wraper bg-parallax bg-top-center" data-stellar-background-ratio="0.5" style="background-image:url(images/banner/8.jpg);">
    <div class="overlay-main bg-black opacity-07"></div>
    <div class="container">
        <div class="sx-bnr-inr-entry">
            <div class="banner-title-outer">
                <div class="banner-title-name">
                    <h2 class="m-tb0">@sotec_web.Resources.Dil.BLOG</h2>
                </div>
            </div>
            <div>
                <ul class="sx-breadcrumb breadcrumb-style-2">
                    <li><a href="@Url.Action("Index", "Inteshape")">@sotec_web.Resources.Dil.ANA_SAYFA</a></li>
                    <li>@sotec_web.Resources.Dil.BLOG</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="section-full p-tb80 inner-page-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-sm-12">
                <div class="news-listing ">
                    @foreach (DataRow dr_blog_item in dt_son_bloglar.Rows)
                    {
                        <div class="blog-post blog-lg date-style-3 block-shadow">
                            <div class="sx-post-media sx-img-effect zoom-slow">
                                <a href="@Url.Action("Blog", "Inteshape", new { id = dr_blog_item["blog_id"] })"><img src="~/admin_src/images/blog/kucuk/@dr_blog_item["gorsel"]" alt=""></a>
                            </div>
                            <div class="sx-post-info  bg-white">
                                <div class="sx-post-meta ">
                                    <ul>
                                        <li class="post-date"> @(Convert.ToDateTime(dr_blog_item["kayit_tarihi"]).ToShortDateString()) </li>
                                        <li class="post-author">@dr_blog_item["ad_soyad"] </li>
                                    </ul>
                                </div>
                                <div class="sx-post-title ">
                                    <h4 class="post-title"><a href="@Url.Action("Blog", "Inteshape", new { id = dr_blog_item["blog_id"] })">@dr_blog_item["baslik"]</a></h4>
                                </div>
                                <div class="sx-post-text">
                                    @{ yazi = rRemScript.Replace(dr_blog_item["yazi"].ToString(), String.Empty);}
                                    <p>@MvcHtmlString.Create(SQL.StripHTML(yazi.Substring(0, yazi.Length < 100 ? yazi.Length : 100)))...</p>
                                </div>
                                <div class="clearfix">
                                    <div class="sx-post-readmore pull-left">
                                        <a href="@Url.Action("Blog", "Inteshape", new { id = dr_blog_item["blog_id"] })" title="@sotec_web.Resources.Dil.DEVAMINI_OKU" rel="bookmark" class="site-button-link">@sotec_web.Resources.Dil.DEVAMINI_OKU</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <ul class="pagination m-b30">
                    @for (int i = 0; i < sayfa_sayisi; i++)
                    {
                        <li class="@(i == sayfa_no ? "active" : "")"><a href="@Url.Action("Blogs", new { id = i, id2 = kategori_id })">@(i + 1)</a></li>
                    }
                </ul>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 sticky_column">
                <div class="side-bar p-a30 bg-gray">

                    <!-- Categories  -->
                    <div class="widget widget_services ">
                        <h4 class="widget-title">@sotec_web.Resources.Dil.KATEGORİLER</h4>
                        <ul class="p-a10 bg-white">
                            @foreach (DataRow dr_kategori_item in dt_haber_kategori.Rows)
                            {
                                <li><a href="@Url.Action("Blogs", "Inteshape", new { id2 = dr_kategori_item["kategori_id"] })">@dr_kategori_item["kategori"]</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

sotec_web/sotec_web/Views/Inteshape/Contact.cshtml
@using System.Data
@using sotec_firma.Helpers
@{
    ViewBag.Title = sotec_web.Resources.Dil.İLETİŞİM;

    string lang = Request.Cookies.Get("MultiLanguageExample").Value;

    DataTable dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND kisa_kod = '" + lang + "'");
    if (dt_dil.Rows.Count <= 0) { dt_dil = SQL.get("SELECT * FROM diller WHERE silindi = 0 AND varsayilan = 1"); }
    DataRow dr_dil = dt_dil.Rows[0];

    DataRow dr_site_bilgileri = SQL.get("SELECT * FROM site_bilgileri WHERE dil_id = " + dr_dil["dil_id"]).Rows[0];
}
<div class="sx-bnr-inr overlay-wraper bg-parallax bg-top-center" data-stellar-background-ratio="0.5" style="background-image:url(images/banner/9.jpg);">
    <div class="overlay-main bg-black opacity-07"></div>
    <div class="container">
        <div class="sx-bnr-inr-entry">
            <div class="banner-title-outer">
                <div class="banner-title-name">
                    <h2 class="m-tb0">@sotec_web.Resources.Dil.İLETİŞİM</h2>
                </div>
            </div>
            <div>
                <ul class="sx-breadcrumb breadcrumb-style-2">
                    <li><a href="@Url.Action("Index", "Inteshape")">@sotec_web.Resources.Dil.ANA_SAYFA</a></li>
                    <li>@sotec_web.Resources.Dil.İLETİŞİM</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- SECTION CONTENTG START -->
<div class="section-full p-tb80 inner-page-padding">
    <!-- LOCATION BLOCK-->
    <div class="container">

        <!-- GOOGLE MAP & CONTACT FORM -->
        <div class="section-content">
            <!-- CONTACT FORM-->
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12">
                    @using (Ajax.BeginForm("MesajGonder", "Inteshape", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divSonuc", OnSuccess = "onAjaxRequestSuccess" }, new { id = "formKapsayici", @class = "contact-form bg-gray p-a30" }))
                    {
                        <input type="hidden" name="kaynak" value="İletişim" />
                        <div class="contact-one">
                            <div class="section-head">
                                <div class="sx-separator-outer separator-left">
                                    <div class="sx-separator bg-white bg-moving bg-repeat-x" style="background-image:url(images/background/cross-line2.png)">
                                        <h3 class="sep-line-one">@sotec_web.Resources.Dil.İLETİŞİM</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input name="ad_soyad" type="text" class="form-control" id="form-blog-reply-name" required placeholder="@sotec_web.Resources.Dil.AD_SOYAD">
                            </div>
                            <div class="form-group">
                                <input name="email" type="email" class="form-control" id="form-blog-reply-email" required placeholder="@sotec_web.Resources.Dil.E_MAİL">
                            </div>
                            <div class="form-group">
                                <input name="telefon" type="tel" class="form-control" id="form-blog-reply-telefon" required placeholder="@sotec_web.Resources.Dil.TELEFON">
                            </div>
                            <div class="form-group">
                                <textarea name="mesaj" rows="4" class="form-control " id="form-blog-reply-message" required placeholder="@sotec_web.Resources.Dil.MESAJ"></textarea>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="site-button btn-half">
                                    <span> @sotec_web.Resources.Dil.GÖNDER</span>
                                </button>
                            </div>

                        </div>
                    }
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="contact-info block-shadow bg-white bg-center p-a40" style="background-image:url(images/background/bg-map.png)">
                        <div>
                            <div class="sx-icon-box-wraper left p-b30">
                                <div class="icon-xs"><i class="fa fa-phone"></i></div>
                                <div class="icon-content">
                                    <h5 class="m-t0">@sotec_web.Resources.Dil.TELEFON</h5>
                                    <p>
                                        @MvcHtmlString.Create((dr_site_bilgileri["telefon"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.TELEFON + ": </span>" + dr_site_bilgileri["telefon"] + "</p>"))
                                        @MvcHtmlString.Create((dr_site_bilgileri["gsm"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.GSM + ": </span>" + dr_site_bilgileri["gsm"] + "</p>"))
                                        @MvcHtmlString.Create((dr_site_bilgileri["fax"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.FAX + ": </span>" + dr_site_bilgileri["fax"] + "</p>"))
                                        @MvcHtmlString.Create((dr_site_bilgileri["whatsapp"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.WHATSAPP + ": </span>" + dr_site_bilgileri["whatsapp"] + "</p>"))
                                    </p>
                                </div>
                            </div>
                            <div class="sx-icon-box-wraper left p-b30">
                                <div class="icon-xs"><i class="fa fa-envelope"></i></div>
                                <div class="icon-content">
                                    <h5 class="m-t0">@sotec_web.Resources.Dil.E_MAİL</h5>
                                    <p>
                                        @MvcHtmlString.Create((dr_site_bilgileri["email"].ToString().Length <= 0 ? "" : "<p><span>" + sotec_web.Resources.Dil.E_MAİL + ": </span> <a href='mailto: " + dr_site_bilgileri["email"] + "'>" + dr_site_bilgileri["email"] + "</a></p>"))
                                    </p>
                                </div>
                            </div>
                            <div class="sx-icon-box-wraper left">
                                <div class="icon-xs"><i class="fa fa-map-marker"></i></div>
                                <div class="icon-content">
                                    <h5 class="m-t0">@sotec_web.Resources.Dil.ADRES</h5>
                                    <p>
                                        @MvcHtmlString.Create((dr_site_bilgileri["adres"].ToString().Length <= 0 ? "" : "<p>" + dr_site_bilgileri["adres"] + "</p>"))
                                        @MvcHtmlString.Create((dr_site_bilgileri["calisma_saatleri"].ToString().Length <= 0 ? "" : "<p>" + dr_site_bilgileri["calisma_saatleri"] + "</p>"))
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>